### ISSUE TITLE
How to change Amazon URLs in Docker?

### ISSUE THREAD

**Issue by N1co93** [thiagobruch/amazon_shopping_list_scrape#1]
Hello,

as I'm living in Germany I have to change the Amazon URLs inside the `scrapeAmazon.js` File.
How can I change this file permanent in Docker? If I would rebuild the Docker container, the changes will get lost.

Maybe you could add the Amazon country as an docker environment parameter?

Thank you

**Comment by thiagobruch** [comment]
Hi @N1c093,

There are two options to "fix" that:

1 -  You download the files, change the URL and build the docker image.
In order to build the image yourself, use the instructions below:
1.1 - Save all the file in a single directory 
1.2 - Edit the scrapeAmazon.js file and replace the URLs
1.3 - Run the following command:
```
docker build -t amazon-scrape-tb .
```
1.4 - It will take a while to create the image (around 850MB) 4 - Once it is completed, run the docker run command with the variables to start the container:
```
docker run -d \
  --name amazon-scraper \
  -e AMZ_LOGIN='<YOUR_AMAZON_EMAIL>' \ # your email address used to login at amazon in this format 'email@email.com' including single quotes.
  -e AMZ_PASS='<YOUR_AMAZON_PASSORD>' \ # your password used to login at amazon in this format 'mypassword1234' including single quotes.
  -e AMZ_SECRET='<YOUR_OTP_APP_SECRET>' \ # your OTP App Secret in this format 'mypassword1234' including single quotes. More instructions below.
  -e HA_WEBHOOK_URL='<HOME_ASSISTANT_WEBHOOK_URL' \ # your Home Assistant Webhook URL including single quotes. More instructions below.
  amazon-scrape-tb
```
*"How can I change this file permanent in Docker? If I would rebuild the Docker container, the changes will get lost."
If you make the change and then rebuild the image, the new image will have the new URLs permanently.

2 - I add the URL, rebuild the image using a variable to point to the country URL
At this time, I only have the US, IT and AU.
And in order to use different URLs, I would have to have an account in several countries in Amazon.

**Comment by N1co93** [comment]
Thank you for your reply. I also did a bit recherche yesterday.
I managed to get the file mounted with docker. So the file is persistent and changes are not destroyed, when I reset the container. https://docs.docker.com/storage/bind-mounts/#choose-the--v-or---mount-flag
This is working fine. 

Thank you for the docker container.
